<a href="https://colab.research.google.com/github/demsaid400-cpu/DI-BOOTCAMP/blob/main/Week5_Day4_Daily_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch scikit-learn pandas numpy joblib gensim spacy -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 73.2 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
import joblib

import warnings
warnings.filterwarnings("ignore")

In [ ]:
import os
import zipfile

zip_path = '/content/archive.zip'
extract_path = '/content/extracted_data'

if os.path.exists(zip_path):
    file_size = os.path.getsize(zip_path)
    print(f"File size: {file_size} bytes")

    if file_size > 0:
        try:
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(extract_path)
            print(f"Files successfully extracted to: {extract_path}")
        except zipfile.BadZipFile:
            print("Error: The file exists but is not a valid zip archive.")
    else:
        print("Error: The file is empty (0 bytes).")
else:
    print(f"Error: File not found at {zip_path}")

File size: 67108864 bytes
Error: The file exists but is not a valid zip archive.

In [ ]:
import os

# Using 7z (7-zip) which is often more successful with non-standard or 'streamed' zip files
print("Attempting extraction with 7z...")
extract_path = '/content/extracted_data'
os.makedirs(extract_path, exist_ok=True)

!7z x /content/archive.zip -o{extract_path} -y

print("\nChecking for extracted files:")
found = False
for root, dirs, files in os.walk(extract_path):
    for file in files:
        print(os.path.join(root, file))
        found = True

if not found:
    print("7z also failed to extract any files. The archive may be part of a split set or severely truncated.")

Attempting extraction with 7z...

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU @ 2.00GHz (50653),ASM,AES-NI)

Scanning the drive for archives:
  0M Scan /content/                   1 file, 67108864 bytes (64 MiB)

Extracting archive: /content/archive.zip
 11% 256 Open             
ERRORS:
Unexpected end of archive

--
Path = /content/archive.zip
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 67129353

 19%     10% 228 - etfs/CORN.csv                         20% 382         29% 513 - etfs/EWS.csv                        37% 659 - etfs/FMF.csv                        45% 780 - etfs/GOVT.csv                         52% 947 - etfs/IECS.csv                         61% 1060 - etfs/IWD.csv                         70% 1166 - etfs/KBWY.csv                          75% 1278 - etfs/MOTO.csv                          82% 1409 - etfs/PID.csv                         90% 1519 - etfs/QID.csv                         96% 1627 - etfs/RWR.csv                        ERROR: Data Error : etfs/SCO.csv
100% 1676 - etfs/SCO.csv                        
Sub items Errors: 1

Archives with Errors: 1

Open Errors: 1

Sub items Errors: 1

Checking for extracted files:
/content/extracted_data/etfs/FLMB.csv
/content/extracted_data/etfs/BND.csv
/content/extracted_data/etfs/IBDN.csv
/content/extracted_data/etfs/DVOL.csv
/content/extracted_data/etfs/MILN.csv
/content/extracted_data/etfs/PKW.csv
/content/extracted_data/etfs/FIW.csv
/content/extracted_data/etfs/CSA.csv
/content/extracted_data/etfs/HEWC.csv
/content/extracted_data/etfs/QLVD.csv
/content/extracted_data/etfs/FLOT.csv
/content/extracted_data/etfs/FITE.csv
/content/extracted_data/etfs/FLRT.csv
/content/extracted_data/etfs/FTSM.csv
/content/extracted_data/etfs/ESG.csv
/content/extracted_data/etfs/DUG.csv
/content/extracted_data/etfs/HSPX.csv
/content/extracted_data/etfs/FXO.csv
/content/extracted_data/etfs/FPX.csv
/content/extracted_data/etfs/EUDG.csv
/content/extracted_data/etfs/LGH.csv
/content/extracted_data/etfs/FTEC.csv
/content/extracted_data/etfs/RNSC.csv
/content/extracted_data/etfs/CIZ.csv
/content/extracted_data/etfs/FAUG.csv
/content/extracted_data/etfs/DEFA.csv
/content/extracted_data/etfs/IBTH.csv
/content/extracted_data/etfs/FLQL.csv
/content/extracted_data/etfs/IXG.csv
/content/extracted_data/etfs/HDEF.csv
/content/extracted_data/etfs/AOA.csv
/content/extracted_data/etfs/KURE.csv
/content/extracted_data/etfs/HMOP.csv
/content/extracted_data/etfs/EEMO.csv
/content/extracted_data/etfs/RBIN.csv
/content/extracted_data/etfs/FVAL.csv
/content/extracted_data/etfs/IPFF.csv
/content/extracted_data/etfs/ESGS.csv
/content/extracted_data/etfs/DMRS.csv
/content/extracted_data/etfs/GREK.csv
/content/extracted_data/etfs/CCOR.csv
/content/extracted_data/etfs/BSJN.csv
/content/extracted_data/etfs/DIVO.csv
/content/extracted_data/etfs/AGT.csv
/content/extracted_data/etfs/RODM.csv
/content/extracted_data/etfs/AOK.csv
/content/extracted_data/etfs/EMXC.csv
/content/extracted_data/etfs/IJUL.csv
/content/extracted_data/etfs/EMIH.csv
/content/extracted_data/etfs/LVHD.csv
/content/extracted_data/etfs/AVDE.csv
/content/extracted_data/etfs/EMIF.csv
/content/extracted_data/etfs/HOLD.csv
/content/extracted_data/etfs/OIL.csv
/content/extracted_data/etfs/IBTG.csv
/content/extracted_data/etfs/ARCM.csv
/content/extracted_data/etfs/FLQM.csv
/content/extracted_data/etfs/EZA.csv
/content/extracted_data/etfs/IYLD.csv
/content/extracted_data/etfs/IWL.csv
/content/extracted_data/etfs/RZV.csv
/content/extracted_data/etfs/BNDW.csv
/content/extracted_data/etfs/IFV.csv
/content/extracted_data/etfs/GEM.csv
/content/extracted_data/etfs/KMED.csv
/content/extracted_data/etfs/IBDT.csv
/content/extracted_data/etfs/KALL.csv
/content/extracted_data/etfs/NUSC.csv
/content/extracted_data/etfs/JNMF.csv
/content/extracted_data/etfs/EWZ.csv
/content/extracted_data/etfs/IQSU.csv
/content/extracted_data/etfs/FNDB.csv
/content/extracted_data/etfs/RNEM.csv
/content/extracted_data/etfs/HYS.csv
/content/extracted_data/etfs/CWS.csv
/content/extracted_data/etfs/DES.csv
/content/extracted_data/etfs/EMAG.csv
/content/extracted_data/etfs/OBOR.csv
/content/extracted_data/etfs/HUSE.csv
/content/extracted_data/etfs/JPED.csv
/content/extracted_data/etfs/FEX.csv
/content/extracted_data/etfs/PPEM.csv
/content/extracted_data/etfs/OEF.csv
/content/extracted_data/etfs/ICOL.csv
/content/extracted_data/etfs/GHYG.csv
/content/extracted_data/etfs/MCHI.csv
/content/extracted_data/etfs/FDD.csv
/content/extracted_data/etfs/AUSF.csv
/content/extracted_data/etfs/IMTM.csv
/content/extracted_data/etfs/MARB.csv
/content/extracted_data/etfs/RYH.csv
/content/extracted_data/etfs/PAWZ.csv
/content/extracted_data/etfs/RTM.csv
/content/extracted_data/etfs/EPV.csv
/content/extracted_data/etfs/FLCB.csv
/content/extracted_data/etfs/AFK.csv
/content/extracted_data/etfs/IQDY.csv
/content/extracted_data/etfs/LQDH.csv
/content/extracted_data/etfs/DVP.csv
/content/extracted_data/etfs/FOVL.csv
/content/extracted_data/etfs/GQRE.csv
/content/extracted_data/etfs/PBE.csv
/content/extracted_data/etfs/RYF.csv
/content/extracted_data/etfs/BBH.csv
/content/extracted_data/etfs/PTF.csv
/content/extracted_data/etfs/AVUV.csv
/content/extracted_data/etfs/PHYL.csv
/content/extracted_data/etfs/FTXH.csv
/content/extracted_data/etfs/FVL.csv
/content/extracted_data/etfs/HERD.csv
/content/extracted_data/etfs/GIGE.csv
/content/extracted_data/etfs/OILK.csv
/content/extracted_data/etfs/DBE.csv
/content/extracted_data/etfs/PJP.csv
/content/extracted_data/etfs/JDST.csv
/content/extracted_data/etfs/JHCS.csv
/content/extracted_data/etfs/FNDC.csv
/content/extracted_data/etfs/JPNL.csv
/content/extracted_data/etfs/INDS.csv
/content/extracted_data/etfs/HYMB.csv
/content/extracted_data/etfs/FFEB.csv
/content/extracted_data/etfs/DVY.csv
/content/extracted_data/etfs/LEAD.csv
/content/extracted_data/etfs/EAGG.csv
/content/extracted_data/etfs/RODE.csv
/content/extracted_data/etfs/IHY.csv
/content/extracted_data/etfs/JPUS.csv
/content/extracted_data/etfs/RVRS.csv
/content/extracted_data/etfs/GNOM.csv
/content/extracted_data/etfs/PAPR.csv
/content/extracted_data/etfs/ISDX.csv
/content/extracted_data/etfs/KOL.csv
/content/extracted_data/etfs/HYGV.csv
/content/extracted_data/etfs/IRBO.csv
/content/extracted_data/etfs/HTRB.csv
/content/extracted_data/etfs/PHDG.csv
/content/extracted_data/etfs/ACWV.csv
/content/extracted_data/etfs/DBMF.csv
/content/extracted_data/etfs/EPP.csv
/content/extracted_data/etfs/ISMD.csv
/content/extracted_data/etfs/PPA.csv
/content/extracted_data/etfs/BWX.csv
/content/extracted_data/etfs/FLAX.csv
/content/extracted_data/etfs/FRI.csv
/content/extracted_data/etfs/DFJ.csv
/content/extracted_data/etfs/OUNZ.csv
/content/extracted_data/etfs/DEEF.csv
/content/extracted_data/etfs/BBEU.csv
/content/extracted_data/etfs/PCEF.csv
/content/extracted_data/etfs/DBJP.csv
/content/extracted_data/etfs/BSMR.csv
/content/extracted_data/etfs/OMFL.csv
/content/extracted_data/etfs/PSMM.csv
/content/extracted_data/etfs/ACT.csv
/content/extracted_data/etfs/OPER.csv
/content/extracted_data/etfs/IETC.csv
/content/extracted_data/etfs/PAK.csv
/content/extracted_data/etfs/LDUR.csv
/content/extracted_data/etfs/EUM.csv
/content/extracted_data/etfs/RCD.csv
/content/extracted_data/etfs/JPMV.csv
/content/extracted_data/etfs/EWT.csv
/content/extracted_data/etfs/BSCM.csv
/content/extracted_data/etfs/FLQH.csv
/content/extracted_data/etfs/DTN.csv
/content/extracted_data/etfs/BJAN.csv
/content/extracted_data/etfs/HFXE.csv
/content/extracted_data/etfs/QWLD.csv
/content/extracted_data/etfs/COMT.csv
/content/extracted_data/etfs/DEM.csv
/content/extracted_data/etfs/SCHF.csv
/content/extracted_data/etfs/GMAN.csv
/content/extracted_data/etfs/GBIL.csv
/content/extracted_data/etfs/EUDV.csv
/content/extracted_data/etfs/MINC.csv
/content/extracted_data/etfs/AMZA.csv
/content/extracted_data/etfs/KORP.csv
/content/extracted_data/etfs/HEWU.csv
/content/extracted_data/etfs/HYG.csv
/content/extracted_data/etfs/IDNA.csv
/content/extracted_data/etfs/FILL.csv
/content/extracted_data/etfs/HAUD.csv
/content/extracted_data/etfs/GNMA.csv
/content/extracted_data/etfs/MOM.csv
/content/extracted_data/etfs/JPN.csv
/content/extracted_data/etfs/EWJE.csv
/content/extracted_data/etfs/IECS.csv
/content/extracted_data/etfs/LDRS.csv
/content/extracted_data/etfs/PXQ.csv
/content/extracted_data/etfs/IXSE.csv
/content/extracted_data/etfs/KBWP.csv
/content/extracted_data/etfs/QAT.csv
/content/extracted_data/etfs/ESPO.csv
/content/extracted_data/etfs/IBDU.csv
/content/extracted_data/etfs/CWB.csv
/content/extracted_data/etfs/OSCV.csv
/content/extracted_data/etfs/CHIQ.csv
/content/extracted_data/etfs/NUSI.csv
/content/extracted_data/etfs/EWZS.csv
/content/extracted_data/etfs/JHMF.csv
/content/extracted_data/etfs/BTEC.csv
/content/extracted_data/etfs/CEMB.csv
/content/extracted_data/etfs/EDEN.csv
/content/extracted_data/etfs/FDEM.csv
/content/extracted_data/etfs/DINT.csv
/content/extracted_data/etfs/ECOZ.csv
/content/extracted_data/etfs/PQLC.csv
/content/extracted_data/etfs/IYF.csv
/content/extracted_data/etfs/PSQ.csv
/content/extracted_data/etfs/PEY.csv
/content/extracted_data/etfs/IVE.csv
/content/extracted_data/etfs/COMB.csv
/content/extracted_data/etfs/CHAD.csv
/content/extracted_data/etfs/NETL.csv
/content/extracted_data/etfs/IWS.csv
/content/extracted_data/etfs/IIGD.csv
/content/extracted_data/etfs/PMOM.csv
/content/extracted_data/etfs/BDRY.csv
/content/extracted_data/etfs/FEMB.csv
/content/extracted_data/etfs/IAI.csv
/content/extracted_data/etfs/BBSA.csv
/content/extracted_data/etfs/PST.csv
/content/extracted_data/etfs/CNCR.csv
/content/extracted_data/etfs/SCC.csv
/content/extracted_data/etfs/OUSA.csv
/content/extracted_data/etfs/RWIU.csv
/content/extracted_data/etfs/JHMA.csv
/content/extracted_data/etfs/CSB.csv
/content/extracted_data/etfs/QINT.csv
/content/extracted_data/etfs/LNGR.csv
/content/extracted_data/etfs/GCOW.csv
/content/extracted_data/etfs/FLSP.csv
/content/extracted_data/etfs/DFEN.csv
/content/extracted_data/etfs/PPH.csv
/content/extracted_data/etfs/RFDI.csv
/content/extracted_data/etfs/RSP.csv
/content/extracted_data/etfs/KFYP.csv
/content/extracted_data/etfs/MXI.csv
/content/extracted_data/etfs/CNXT.csv
/content/extracted_data/etfs/EMGF.csv
/content/extracted_data/etfs/EWK.csv
/content/extracted_data/etfs/PNOV.csv
/content/extracted_data/etfs/FLIN.csv
/content/extracted_data/etfs/RESD.csv
/content/extracted_data/etfs/EFAD.csv
/content/extracted_data/etfs/GSG.csv
/content/extracted_data/etfs/ECH.csv
/content/extracted_data/etfs/LOWC.csv
/content/extracted_data/etfs/CLRG.csv
/content/extracted_data/etfs/CHIS.csv
/content/extracted_data/etfs/DURA.csv
/content/extracted_data/etfs/RWUI.csv
/content/extracted_data/etfs/CHII.csv
/content/extracted_data/etfs/FLLV.csv
/content/extracted_data/etfs/FCAL.csv
/content/extracted_data/etfs/BWZ.csv
/content/extracted_data/etfs/ADRE.csv
/content/extracted_data/etfs/BSJL.csv
/content/extracted_data/etfs/EJUL.csv
/content/extracted_data/etfs/GVI.csv
/content/extracted_data/etfs/FIVA.csv
/content/extracted_data/etfs/PEX.csv
/content/extracted_data/etfs/GOAT.csv
/content/extracted_data/etfs/PGAL.csv
/content/extracted_data/etfs/DOL.csv
/content/extracted_data/etfs/BBRE.csv
/content/extracted_data/etfs/EWJV.csv
/content/extracted_data/etfs/HYDW.csv
/content/extracted_data/etfs/HYND.csv
/content/extracted_data/etfs/DBO.csv
/content/extracted_data/etfs/CHIH.csv
/content/extracted_data/etfs/INFR.csv
/content/extracted_data/etfs/ILF.csv
/content/extracted_data/etfs/FXC.csv
/content/extracted_data/etfs/FTXR.csv
/content/extracted_data/etfs/ETHO.csv
/content/extracted_data/etfs/GBUY.csv
/content/extracted_data/etfs/CHIL.csv
/content/extracted_data/etfs/GDMA.csv
/content/extracted_data/etfs/LACK.csv
/content/extracted_data/etfs/SCHO.csv
/content/extracted_data/etfs/BGRN.csv
/content/extracted_data/etfs/PSK.csv
/content/extracted_data/etfs/FXH.csv
/content/extracted_data/etfs/BLES.csv
/content/extracted_data/etfs/BZQ.csv
/content/extracted_data/etfs/NANR.csv
/content/extracted_data/etfs/FWDB.csv
/content/extracted_data/etfs/BOSS.csv
/content/extracted_data/etfs/IXC.csv
/content/extracted_data/etfs/KGRN.csv
/content/extracted_data/etfs/IHF.csv
/content/extracted_data/etfs/HCRB.csv
/content/extracted_data/etfs/EWGS.csv
/content/extracted_data/etfs/IVOV.csv
/content/extracted_data/etfs/FLSW.csv
/content/extracted_data/etfs/FDHY.csv
/content/extracted_data/etfs/CHIX.csv
/content/extracted_data/etfs/DXD.csv
/content/extracted_data/etfs/HYZD.csv
/content/extracted_data/etfs/RWK.csv
/content/extracted_data/etfs/CYB.csv
/content/extracted_data/etfs/MFUS.csv
/content/extracted_data/etfs/AGND.csv
/content/extracted_data/etfs/FFTI.csv
/content/extracted_data/etfs/HTUS.csv
/content/extracted_data/etfs/DEUS.csv
/content/extracted_data/etfs/HYLV.csv
/content/extracted_data/etfs/RWM.csv
/content/extracted_data/etfs/PVAL.csv
/content/extracted_data/etfs/KSA.csv
/content/extracted_data/etfs/ONEY.csv
/content/extracted_data/etfs/EFAS.csv
/content/extracted_data/etfs/SBB.csv
/content/extracted_data/etfs/EXI.csv
/content/extracted_data/etfs/LVHB.csv
/content/extracted_data/etfs/FDVV.csv
/content/extracted_data/etfs/PACA.csv
/content/extracted_data/etfs/CHIR.csv
/content/extracted_data/etfs/CACG.csv
/content/extracted_data/etfs/MDYV.csv
/content/extracted_data/etfs/EJAN.csv
/content/extracted_data/etfs/MOTO.csv
/content/extracted_data/etfs/FUTY.csv
/content/extracted_data/etfs/RFEM.csv
/content/extracted_data/etfs/FFIU.csv
/content/extracted_data/etfs/IYH.csv
/content/extracted_data/etfs/EIDO.csv
/content/extracted_data/etfs/CLIX.csv
/content/extracted_data/etfs/DWLD.csv
/content/extracted_data/etfs/FMHI.csv
/content/extracted_data/etfs/RNDV.csv
/content/extracted_data/etfs/PBTP.csv
/content/extracted_data/etfs/EMB.csv
/content/extracted_data/etfs/FLLA.csv
/content/extracted_data/etfs/ECON.csv
/content/extracted_data/etfs/EWC.csv
/content/extracted_data/etfs/ITA.csv
/content/extracted_data/etfs/FSMD.csv
/content/extracted_data/etfs/ESGE.csv
/content/extracted_data/etfs/KIE.csv
/content/extracted_data/etfs/PBND.csv
/content/extracted_data/etfs/EZU.csv
/content/extracted_data/etfs/DOG.csv
/content/extracted_data/etfs/QDF.csv
/content/extracted_data/etfs/DYLS.csv
/content/extracted_data/etfs/GFIN.csv
/content/extracted_data/etfs/OLD.csv
/content/extracted_data/etfs/ROBO.csv
/content/extracted_data/etfs/IJT.csv
/content/extracted_data/etfs/FTLB.csv
/content/extracted_data/etfs/GUNR.csv
/content/extracted_data/etfs/EMFM.csv
/content/extracted_data/etfs/PRFZ.csv
/content/extracted_data/etfs/IBMQ.csv
/content/extracted_data/etfs/RETL.csv
/content/extracted_data/etfs/BMAR.csv
/content/extracted_data/etfs/RPV.csv
/content/extracted_data/etfs/KNG.csv
/content/extracted_data/etfs/MINT.csv
/content/extracted_data/etfs/PIO.csv
/content/extracted_data/etfs/ISEM.csv
/content/extracted_data/etfs/NUMG.csv
/content/extracted_data/etfs/BIL.csv
/content/extracted_data/etfs/IBMM.csv
/content/extracted_data/etfs/JCPB.csv
/content/extracted_data/etfs/RWGV.csv
/content/extracted_data/etfs/FMB.csv
/content/extracted_data/etfs/CPER.csv
/content/extracted_data/etfs/DGRS.csv
/content/extracted_data/etfs/AGQ.csv
/content/extracted_data/etfs/EMNT.csv
/content/extracted_data/etfs/IVOL.csv
/content/extracted_data/etfs/JHEM.csv
/content/extracted_data/etfs/FLKR.csv
/content/extracted_data/etfs/BDCY.csv
/content/extracted_data/etfs/DIA.csv
/content/extracted_data/etfs/IWM.csv
/content/extracted_data/etfs/FAN.csv
/content/extracted_data/etfs/HEZU.csv
/content/extracted_data/etfs/PFM.csv
/content/extracted_data/etfs/EGPT.csv
/content/extracted_data/etfs/FPEI.csv
/content/extracted_data/etfs/GMF.csv
/content/extracted_data/etfs/BSCR.csv
/content/extracted_data/etfs/CNYA.csv
/content/extracted_data/etfs/MLTI.csv
/content/extracted_data/etfs/GCC.csv
/content/extracted_data/etfs/IDHD.csv
/content/extracted_data/etfs/PTBD.csv
/content/extracted_data/etfs/SCHV.csv
/content/extracted_data/etfs/QQH.csv
/content/extracted_data/etfs/HEWL.csv
/content/extracted_data/etfs/IGSB.csv
/content/extracted_data/etfs/ARKF.csv
/content/extracted_data/etfs/ELD.csv
/content/extracted_data/etfs/GSIE.csv
/content/extracted_data/etfs/QQEW.csv
/content/extracted_data/etfs/PID.csv
/content/extracted_data/etfs/JKK.csv
/content/extracted_data/etfs/EWP.csv
/content/extracted_data/etfs/GSEU.csv
/content/extracted_data/etfs/SCHJ.csv
/content/extracted_data/etfs/CXSE.csv
/content/extracted_data/etfs/DRIP.csv
/content/extracted_data/etfs/BNDC.csv
/content/extracted_data/etfs/FEZ.csv
/content/extracted_data/etfs/PPSC.csv
/content/extracted_data/etfs/IFRA.csv
/content/extracted_data/etfs/ISTB.csv
/content/extracted_data/etfs/BSCN.csv
/content/extracted_data/etfs/HECO.csv
/content/extracted_data/etfs/BJUN.csv
/content/extracted_data/etfs/IGHG.csv
/content/extracted_data/etfs/PSCF.csv
/content/extracted_data/etfs/PSLV.csv
/content/extracted_data/etfs/RWL.csv
/content/extracted_data/etfs/ALTS.csv
/content/extracted_data/etfs/RTH.csv
/content/extracted_data/etfs/GNR.csv
/content/extracted_data/etfs/ALTY.csv
/content/extracted_data/etfs/DXGE.csv
/content/extracted_data/etfs/EQWL.csv
/content/extracted_data/etfs/HIBS.csv
/content/extracted_data/etfs/QLD.csv
/content/extracted_data/etfs/EFV.csv
/content/extracted_data/etfs/LSAF.csv
/content/extracted_data/etfs/JKI.csv
/content/extracted_data/etfs/CANE.csv
/content/extracted_data/etfs/AAXJ.csv
/content/extracted_data/etfs/BBCA.csv
/content/extracted_data/etfs/HDAW.csv
/content/extracted_data/etfs/HYUP.csv
/content/extracted_data/etfs/IFGL.csv
/content/extracted_data/etfs/DMRL.csv
/content/extracted_data/etfs/EMDV.csv
/content/extracted_data/etfs/DMRE.csv
/content/extracted_data/etfs/PQSG.csv
/content/extracted_data/etfs/BLCN.csv
/content/extracted_data/etfs/LGLV.csv
/content/extracted_data/etfs/LCR.csv
/content/extracted_data/etfs/RISE.csv
/content/extracted_data/etfs/BSCE.csv
/content/extracted_data/etfs/ARKQ.csv
/content/extracted_data/etfs/DVLU.csv
/content/extracted_data/etfs/AIQ.csv
/content/extracted_data/etfs/FIBR.csv
/content/extracted_data/etfs/PFEB.csv
/content/extracted_data/etfs/ROUS.csv
/content/extracted_data/etfs/RNDM.csv
/content/extracted_data/etfs/IYW.csv
/content/extracted_data/etfs/IEV.csv
/content/extracted_data/etfs/LMLB.csv
/content/extracted_data/etfs/FSMB.csv
/content/extracted_data/etfs/GDNA.csv
/content/extracted_data/etfs/JETS.csv
/content/extracted_data/etfs/EDOW.csv
/content/extracted_data/etfs/FTXO.csv
/content/extracted_data/etfs/JXI.csv
/content/extracted_data/etfs/BSMO.csv
/content/extracted_data/etfs/IBTE.csv
/content/extracted_data/etfs/REZ.csv
/content/extracted_data/etfs/FLM.csv
/content/extracted_data/etfs/CURE.csv
/content/extracted_data/etfs/AVEM.csv
/content/extracted_data/etfs/FKU.csv
/content/extracted_data/etfs/FLMX.csv
/content/extracted_data/etfs/HOMZ.csv
/content/extracted_data/etfs/OVM.csv
/content/extracted_data/etfs/JHSC.csv
/content/extracted_data/etfs/SCHP.csv
/content/extracted_data/etfs/POTX.csv
/content/extracted_data/etfs/IEME.csv
/content/extracted_data/etfs/RFAP.csv
/content/extracted_data/etfs/ROMO.csv
/content/extracted_data/etfs/BBJP.csv
/content/extracted_data/etfs/BFEB.csv
/content/extracted_data/etfs/BUY.csv

In [ ]:
import os
import pandas as pd

extracted_dir = '/content/extracted_data/etfs'
if os.path.exists(extracted_dir):
    all_files = sorted(os.listdir(extracted_dir))
    print(f"Total files extracted: {len(all_files)}")
    print(f"First 10 files: {all_files[:10]}")

    # Load a sample file to verify content
    sample_file = os.path.join(extracted_dir, all_files[0])
    print(f"\nPreviewing {all_files[0]}:")
    df_sample = pd.read_csv(sample_file)
    display(df_sample.head())
else:
    print("Extraction directory not found.")

Total files extracted: 1677
First 10 files: ['AAAU.csv', 'AADR.csv', 'AAXJ.csv', 'ABEQ.csv', 'ACES.csv', 'ACIO.csv', 'ACSG.csv', 'ACSI.csv', 'ACT.csv', 'ACWF.csv']

Previewing AAAU.csv:

         Date   Open   High    Low  Close  Adj Close  Volume
0  2018-08-15  11.84  11.84  11.74  11.74      11.74   27300
1  2018-08-16  11.78  11.80  11.74  11.74      11.74  428400
2  2018-08-17  11.80  11.82  11.77  11.82      11.82   52400
3  2018-08-20  11.88  11.91  11.85  11.90      11.90   28700
4  2018-08-21  11.92  11.95  11.89  11.93      11.93   30600

In [ ]:
print(df.shape)

print(df.info())

df.head()

In [17]:
# On définit df à partir de l'échantillon chargé précédemment
df = df_sample

# Supprimer les colonnes inutiles
columns_to_drop = []

for col in ['Date', 'Name', 'Symbol']:
    if col in df.columns:
        columns_to_drop.append(col)

df.drop(columns=columns_to_drop, inplace=True)


# Créer la variable cible : prix de fermeture du lendemain
df['Target'] = df['Close'].shift(-1)

# Supprimer la dernière ligne vide
df.dropna(inplace=True)

df.head()

    Open   High    Low  Close  Adj Close  Volume  Target
0  11.84  11.84  11.74  11.74      11.74   27300   11.74
1  11.78  11.80  11.74  11.74      11.74  428400   11.82
2  11.80  11.82  11.77  11.82      11.82   52400   11.90
3  11.88  11.91  11.85  11.90      11.90   28700   11.93
4  11.92  11.95  11.89  11.93      11.93   30600   11.96

In [18]:
scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(df)

scaled_df = pd.DataFrame(
    scaled_data,
    columns=df.columns
)

scaled_df.head()

       Open      High       Low     Close  Adj Close    Volume    Target
0  0.011929  0.007921  0.000000  0.000000   0.000000  0.012286  0.000000
1  0.000000  0.000000  0.000000  0.000000   0.000000  0.193460  0.016032
2  0.003976  0.003960  0.006198  0.016032   0.016032  0.023623  0.032064
3  0.019881  0.021782  0.022727  0.032064   0.032064  0.012918  0.038076
4  0.027833  0.029703  0.030992  0.038076   0.038076  0.013777  0.044088

In [19]:
sequence_length = 30

X = []
y = []

data = scaled_df.values

for i in range(len(data) - sequence_length):

    X.append(
        data[i:i + sequence_length, :-1]
    )

    y.append(
        data[i + sequence_length, -1]
    )

X = np.array(X)
y = np.array(y)

print("X shape :", X.shape)
print("y shape :", y.shape)

X shape : (379, 30, 6)
y shape : (379,)

In [20]:
total_size = len(X)

train_size = int(total_size * 0.7)
val_size = int(total_size * 0.15)


X_train = X[:train_size]
y_train = y[:train_size]


X_val = X[train_size:train_size + val_size]
y_val = y[train_size:train_size + val_size]


X_test = X[train_size + val_size:]
y_test = y[train_size + val_size:]


print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

Train: (265, 30, 6)
Validation: (56, 30, 6)
Test: (58, 30, 6)

In [21]:
class StockDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [22]:
batch_size = 32

train_dataset = StockDataset(X_train, y_train)
val_dataset = StockDataset(X_val, y_val)
test_dataset = StockDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [23]:
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=2, dropout=0.2):
        super(LSTMModel, self).__init__()

        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout
        )

        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        out = self.fc(out)
        return out.squeeze()

In [24]:
input_size = X_train.shape[2]

model = LSTMModel(input_size=input_size)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [26]:
epochs = 20

for epoch in range(epochs):
    model.train()
    train_loss = 0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()

        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)

        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Validation
    model.eval()
    val_loss = 0

    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            val_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")

Epoch 1/20 | Train Loss: 0.0165 | Val Loss: 0.0041
Epoch 2/20 | Train Loss: 0.0150 | Val Loss: 0.0038
Epoch 3/20 | Train Loss: 0.0156 | Val Loss: 0.0041
Epoch 4/20 | Train Loss: 0.0140 | Val Loss: 0.0038
Epoch 5/20 | Train Loss: 0.0149 | Val Loss: 0.0037
Epoch 6/20 | Train Loss: 0.0142 | Val Loss: 0.0037
Epoch 7/20 | Train Loss: 0.0150 | Val Loss: 0.0038
Epoch 8/20 | Train Loss: 0.0142 | Val Loss: 0.0037
Epoch 9/20 | Train Loss: 0.0143 | Val Loss: 0.0039
Epoch 10/20 | Train Loss: 0.0126 | Val Loss: 0.0037
Epoch 11/20 | Train Loss: 0.0136 | Val Loss: 0.0037
Epoch 12/20 | Train Loss: 0.0134 | Val Loss: 0.0037
Epoch 13/20 | Train Loss: 0.0149 | Val Loss: 0.0039
Epoch 14/20 | Train Loss: 0.0136 | Val Loss: 0.0037
Epoch 15/20 | Train Loss: 0.0144 | Val Loss: 0.0039
Epoch 16/20 | Train Loss: 0.0137 | Val Loss: 0.0037
Epoch 17/20 | Train Loss: 0.0137 | Val Loss: 0.0038
Epoch 18/20 | Train Loss: 0.0131 | Val Loss: 0.0037
Epoch 19/20 | Train Loss: 0.0145 | Val Loss: 0.0038
Epoch 20/20 | Train Loss: 0.0129 | Val Loss: 0.0037

In [27]:
model.eval()

predictions = []
actuals = []

with torch.no_grad():
    for X_batch, y_batch in test_loader:
        outputs = model(X_batch)
        predictions.extend(outputs.numpy())
        actuals.extend(y_batch.numpy())

r2 = r2_score(actuals, predictions)

print("R² Score:", r2)

R² Score: -0.18612184908909524

In [28]:
torch.save(model.state_dict(), "lstm_stock_model.pth")

joblib.dump(scaler, "scaler.pkl")

print("Modèle et scaler sauvegardés !")

Modèle et scaler sauvegardés !

In [29]:
model.eval()

sample = torch.tensor(X_test[0:1], dtype=torch.float32)

with torch.no_grad():
    pred = model(sample)

print("Prediction :", pred.item())

Prediction : 0.7140852808952332